from knowledge.schema import KnowledgeRecord


KNOWLEDGE_RECORDS = [
    KnowledgeRecord(
        rule_id="SEC-GEN-001",
        title="Avoid hardcoded secrets",
        category="security",
        subcategory="secrets",
        language=["any"],
        framework=["any"],
        severity="critical",
        description="Credentials, API keys, tokens, and passwords must not be committed in source code.",
        why_it_matters="Leaked secrets allow unauthorized access and are difficult to fully rotate after exposure.",
        bad_patterns=["password = 'literal'", "api_key = 'literal'", "const token = 'literal'"],
        good_patterns=["Read secrets from environment variables or a managed secret store."],
        exceptions=["Clearly fake examples in documentation or tests should not be treated as live credentials."],
        detection_hints=["credential-like assignment to a long quoted literal", "exclude comments and obvious examples"],
        fix_strategy="Move the value to environment-backed configuration and rotate any exposed credential.",
        production_impact="Secret exposure can compromise accounts, data, and downstream services.",
        standards=[{"name": "CWE", "reference": "CWE-798 Use of Hard-coded Credentials"}],
        source_urls=["https://cwe.mitre.org/data/definitions/798.html"],
        content="Hardcoded secrets are production security defects unless the surrounding evidence proves the value is non-sensitive.",
    ),
    KnowledgeRecord(
        rule_id="SEC-PY-002",
        title="Avoid command execution through a shell",
        category="security",
        subcategory="command-injection",
        language=["python"],
        framework=["any"],
        severity="high",
        description="Python subprocess calls with shell=True execute through a shell and expand metacharacters.",
        why_it_matters="If user-controlled data reaches the command string, attackers can execute arbitrary commands.",
        bad_patterns=["subprocess.run(user_input, shell=True)", "subprocess.Popen(cmd, shell=True)"],
        good_patterns=["Pass an argv list with shell=False and validate allowed arguments."],
        exceptions=["Static literal maintenance scripts outside request paths may be lower risk but still need review."],
        detection_hints=["subprocess.* shell=True", "os.system", "commands built from request/query/form values"],
        fix_strategy="Replace shell=True with a list of fixed executable and validated arguments.",
        production_impact="Remote command execution can lead to full host compromise.",
        standards=[{"name": "CWE", "reference": "CWE-78 OS Command Injection"}],
        source_urls=["https://cwe.mitre.org/data/definitions/78.html"],
        content="Evidence should include both the dangerous API and data-flow or route context when available.",
    ),
    KnowledgeRecord(
        rule_id="PERF-WEB-001",
        title="Move expensive request-path work to background workers",
        category="performance",
        subcategory="blocking-work",
        language=["javascript", "typescript", "python"],
        framework=["express", "fastapi", "node"],
        severity="medium",
        description="CPU-heavy or long-running tasks in HTTP handlers block responses and reduce throughput.",
        why_it_matters="Users experience timeouts and the server can become unavailable under modest concurrency.",
        bad_patterns=["image/video processing inside a route", "large synchronous loops in a controller"],
        good_patterns=["Enqueue work to a background worker and return a job id/status endpoint."],
        exceptions=["Small bounded operations with measured latency may be acceptable."],
        detection_hints=["route handler calls image processing, crypto loops, sync filesystem, or repeated external calls"],
        fix_strategy="Introduce a queue/worker using the project's existing runtime conventions before adding new infrastructure.",
        production_impact="Prevents request timeouts and improves resilience under load.",
        standards=[{"name": "General", "reference": "Web request latency and background job design"}],
        source_urls=[],
        content="Use this when evidence shows expensive work runs synchronously in a request path.",
    ),
    KnowledgeRecord(
        rule_id="ARCH-GEN-001",
        title="Keep route handlers thin",
        category="architecture",
        subcategory="separation-of-concerns",
        language=["javascript", "typescript", "python"],
        framework=["express", "fastapi"],
        severity="medium",
        description="Routes should coordinate validation/auth and delegate business logic to services.",
        why_it_matters="Controllers that mix HTTP, business, and database logic become hard to test and change safely.",
        bad_patterns=["database writes and business decisions directly inside route handlers"],
        good_patterns=["route -> middleware/validation -> controller/service -> repository/database"],
        exceptions=["Tiny endpoints may inline trivial reads if the project convention already does so."],
        detection_hints=["route decorators or app.METHOD calls containing database calls or large logic blocks"],
        fix_strategy="Extract cohesive logic into the existing service/repository layer rather than introducing broad rewrites.",
        production_impact="Improves testability, change isolation, and incident debugging.",
        standards=[{"name": "General", "reference": "Separation of concerns"}],
        source_urls=[],
        content="Architecture findings require file/context evidence, not generic recommendations.",
    ),
    KnowledgeRecord(
        rule_id="API-GEN-001",
        title="Validate external input at API boundaries",
        category="api_design",
        subcategory="validation",
        language=["javascript", "typescript", "python"],
        framework=["express", "fastapi"],
        severity="high",
        description="Requests should be validated before data reaches services or persistence.",
        why_it_matters="Missing validation allows malformed data, injection payloads, and inconsistent records.",
        bad_patterns=["route directly uses req.body or request.json without schema/middleware"],
        good_patterns=["Pydantic models, Zod/Joi schemas, or explicit validation middleware before handlers"],
        exceptions=["Read-only endpoints with no external parameters may not need a schema."],
        detection_hints=["route middleware chain lacks validators; handler writes request fields to db"],
        fix_strategy="Use the validation approach already present in the project and verify middleware order.",
        production_impact="Reduces security defects and production data integrity failures.",
        standards=[{"name": "OWASP", "reference": "OWASP API Security Top 10"}],
        source_urls=["https://owasp.org/API-Security/"],
        content="Search related middleware before claiming validation is missing.",
    ),

    # ---- security: authentication ----
    KnowledgeRecord(
        rule_id="SEC-AUTH-001",
        title="Hash passwords with a slow, salted algorithm",
        category="security",
        subcategory="authentication",
        language=["any"],
        framework=["any"],
        severity="critical",
        description="Passwords must be hashed with bcrypt/argon2/scrypt, never stored plain or with a fast general-purpose hash.",
        why_it_matters="MD5/SHA1/SHA256 are fast to brute-force at scale; a database leak becomes a mass password compromise.",
        bad_patterns=["hashlib.sha256(password).hexdigest()", "md5(password)", "storing password as plaintext column"],
        good_patterns=["bcrypt.hashpw (Python passlib/bcrypt)", "argon2-cffi", "bcryptjs/argon2 (Node)", "Django's built-in PBKDF2/Argon2 hasher"],
        exceptions=["Only applies when the project actually implements its own authentication/password storage."],
        detection_hints=["password field assigned the output of hashlib.md5/sha1/sha256 directly", "raw password column with no hashing call in the write path"],
        fix_strategy="Use the framework's built-in password hasher (Django) or an established slow-hash library (bcrypt/argon2); never invent a custom scheme.",
        production_impact="A single database leak can expose every user's real password after offline cracking.",
        standards=[{"name": "OWASP", "reference": "OWASP Password Storage Cheat Sheet"}],
        source_urls=["https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html"],
        content="Only flag when the project owns password storage; do not flag OAuth/SSO-only apps that never touch a password.",
    ),
    KnowledgeRecord(
        rule_id="SEC-AUTH-002",
        title="Access/refresh tokens must expire and rotate",
        category="security",
        subcategory="authentication",
        language=["any"],
        framework=["any"],
        severity="high",
        description="JWTs and session tokens need a short expiry; refresh tokens should rotate on use and be revocable.",
        why_it_matters="A non-expiring or non-revocable token remains valid forever once stolen, even after a password change.",
        bad_patterns=["jwt.sign(payload, secret) with no expiresIn/exp claim", "long-lived static API token with no rotation path"],
        good_patterns=["short exp on access tokens (minutes), longer-lived rotated refresh token, server-side revocation list/session store"],
        exceptions=["Machine-to-machine service tokens scoped and rotated via a secret manager are a separate, acceptable pattern."],
        detection_hints=["jwt.sign/jwt.encode call without exp/expiresIn", "no refresh/revocation endpoint despite issuing long-lived tokens"],
        fix_strategy="Add an expiry claim, implement refresh rotation, and support server-side revocation for compromised tokens.",
        production_impact="Limits the blast radius of a stolen token to a bounded time window.",
        standards=[{"name": "OWASP", "reference": "OWASP Session Management Cheat Sheet"}],
        source_urls=["https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html"],
        content="Only applies when the project issues its own tokens/sessions.",
    ),
    KnowledgeRecord(
        rule_id="SEC-AUTH-003",
        title="Session/auth cookies need HttpOnly, Secure, SameSite",
        category="security",
        subcategory="authentication",
        language=["any"],
        framework=["any"],
        severity="high",
        description="Cookies carrying session or auth state should be HttpOnly, Secure, and SameSite=Lax/Strict.",
        why_it_matters="Missing HttpOnly lets XSS steal the session; missing Secure lets it leak over plain HTTP; missing SameSite widens CSRF exposure.",
        bad_patterns=["res.cookie('session', token)  // no options object", "Set-Cookie without HttpOnly/Secure/SameSite attributes"],
        good_patterns=["res.cookie('session', token, {httpOnly: true, secure: true, sameSite: 'lax'})", "FastAPI/Starlette Response.set_cookie(httponly=True, secure=True, samesite='lax')"],
        exceptions=["Non-sensitive cookies (UI preferences, locale) don't need these flags."],
        detection_hints=["cookie/session-setting call for an auth/session value with no security attributes present"],
        fix_strategy="Add HttpOnly, Secure, and an explicit SameSite attribute to any cookie carrying auth/session state.",
        production_impact="Reduces session-hijacking and CSRF exposure for authenticated users.",
        standards=[{"name": "OWASP", "reference": "OWASP Session Management Cheat Sheet"}],
        source_urls=["https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html"],
        content="Only flag the cookie that actually carries the session/auth token, not every cookie in the project.",
    ),
    KnowledgeRecord(
        rule_id="SEC-AUTHZ-001",
        title="Check resource ownership, not just authentication",
        category="security",
        subcategory="authorization",
        language=["any"],
        framework=["any"],
        severity="high",
        description="An endpoint that accepts a resource id must verify the caller owns/may access that specific resource (avoid IDOR), and admin-only routes must check role, not just a valid session.",
        why_it_matters="Authentication proves who the caller is; without an authorization check, any logged-in user can read or modify any other user's data by changing an id.",
        bad_patterns=["def get_order(order_id): return db.orders.find_one({'_id': order_id})  # no owner check", "admin route guarded only by @login_required, no role check"],
        good_patterns=["query scoped by both resource id AND current_user.id/organization_id", "explicit role/permission check before admin actions"],
        exceptions=["Public or intentionally shared resources (public posts, published content) don't need an ownership check."],
        detection_hints=["handler fetches by path/query id with no filter on the authenticated user", "role check absent on a route named /admin/* or similar"],
        fix_strategy="Scope every by-id lookup to the authenticated principal, and add an explicit role/permission check to privileged routes.",
        production_impact="Prevents horizontal privilege escalation (one user reading/editing another user's data) and vertical escalation to admin actions.",
        standards=[{"name": "OWASP", "reference": "OWASP Top 10 A01:2021 Broken Access Control"}],
        source_urls=["https://owasp.org/Top10/A01_2021-Broken_Access_Control/"],
        content="Requires seeing both the route and the query/filter it uses — do not flag from the route signature alone.",
    ),

    # ---- security: injection / web ----
    KnowledgeRecord(
        rule_id="SEC-WEB-004",
        title="Build database queries with parameters, not string interpolation",
        category="security",
        subcategory="injection",
        language=["any"],
        framework=["any"],
        severity="critical",
        description="SQL must use parameterized queries/ORM bindings; MongoDB queries must not pass raw user objects (e.g. spreading req.body) into a filter.",
        why_it_matters="String-built SQL allows classic SQL injection; passing an unfiltered object into a Mongo query lets an attacker inject operators like $ne/$gt to bypass logic.",
        bad_patterns=["f\"SELECT * FROM users WHERE id = {user_id}\"", "query = \"...\" + user_input", "db.users.find({...req.body})  // raw client object as filter"],
        good_patterns=["parameterized query / ORM query builder (SQLAlchemy, Prisma, Sequelize)", "explicit field allowlist before building a Mongo filter, or a validated schema (Pydantic/Zod) first"],
        exceptions=["Constant, non-user-derived SQL/query fragments are not injection risk."],
        detection_hints=["SQL string built via f-string/concatenation containing a variable", "Mongo filter object built directly from request body/query without whitelisting"],
        fix_strategy="Switch to parameterized queries or the ORM's query builder; for Mongo, validate/allowlist fields before using them in a filter.",
        production_impact="Prevents data exfiltration, auth bypass, and destructive queries via injection.",
        standards=[{"name": "CWE", "reference": "CWE-89 SQL Injection / CWE-943 NoSQL Injection"}],
        source_urls=["https://cwe.mitre.org/data/definitions/89.html"],
        content="Evidence must show user-controlled data reaching the query, not just any SQL/query construction.",
    ),
    KnowledgeRecord(
        rule_id="SEC-WEB-005",
        title="Escape or sanitize user content before rendering as HTML",
        category="security",
        subcategory="xss",
        language=["javascript", "typescript", "python"],
        framework=["react", "express", "django", "fastapi"],
        severity="high",
        description="User-supplied content rendered into HTML must be escaped by default, or explicitly sanitized when raw HTML is required.",
        why_it_matters="Unescaped output lets an attacker inject script that runs in another user's browser session (stored/reflected XSS).",
        bad_patterns=["dangerouslySetInnerHTML={{__html: userContent}}", "element.innerHTML = userInput", "server template auto-escaping disabled (|safe, {% autoescape off %})"],
        good_patterns=["render user content as text (React's default JSX escaping)", "sanitize with DOMPurify before any dangerouslySetInnerHTML use"],
        exceptions=["Content that is never derived from user/external input (static app copy) is not an XSS risk."],
        detection_hints=["dangerouslySetInnerHTML/innerHTML assignment fed by request data, DB content originally from users, or query params"],
        fix_strategy="Render as plain text by default; if raw HTML is genuinely required, sanitize with an allowlist-based library first.",
        production_impact="Prevents session/token theft and account takeover via injected client-side script.",
        standards=[{"name": "OWASP", "reference": "OWASP Top 10 A03:2021 Injection (XSS)"}],
        source_urls=["https://owasp.org/www-community/attacks/xss/"],
        content="Trace the content back to a user/external source before flagging — static, developer-authored HTML is not XSS.",
    ),
    KnowledgeRecord(
        rule_id="SEC-WEB-006",
        title="Protect state-changing endpoints against CSRF when using cookie auth",
        category="security",
        subcategory="csrf",
        language=["any"],
        framework=["express", "django", "fastapi"],
        severity="medium",
        description="If the session/auth is carried in a cookie sent automatically by the browser, state-changing (POST/PUT/DELETE) endpoints need CSRF protection.",
        why_it_matters="Without it, a malicious page can trigger authenticated requests against the app using the victim's browser cookie.",
        bad_patterns=["cookie-based session with no CSRF token/middleware and SameSite not set to Strict/Lax"],
        good_patterns=["CSRF token middleware (csurf/Django's CsrfViewMiddleware) or SameSite=Strict/Lax cookies for pure cookie auth", "bearer-token auth in an Authorization header is inherently not CSRF-vulnerable"],
        exceptions=["APIs authenticated purely via an Authorization header (no ambient cookie) are not CSRF-vulnerable and should not be flagged."],
        detection_hints=["session/auth cookie set without SameSite, and no csrf middleware present in the route chain"],
        fix_strategy="Add CSRF token verification for cookie-authenticated mutating routes, or move to SameSite=Strict plus verifying a custom header.",
        production_impact="Prevents attacker-triggered actions performed as an unwitting logged-in user.",
        standards=[{"name": "OWASP", "reference": "OWASP CSRF Prevention Cheat Sheet"}],
        source_urls=["https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html"],
        content="Do not flag token/header-based (non-cookie) authentication schemes.",
    ),
    KnowledgeRecord(
        rule_id="SEC-WEB-007",
        title="Validate/allowlist server-side requests to user-supplied URLs",
        category="security",
        subcategory="ssrf",
        language=["any"],
        framework=["any"],
        severity="high",
        description="When the server fetches a URL supplied by the client (webhooks, image-by-URL, link previews), it must restrict scheme/host/IP range.",
        why_it_matters="Without validation an attacker can make the server request internal services, cloud metadata endpoints, or bypass network segmentation (SSRF).",
        bad_patterns=["requests.get(user_supplied_url)", "httpx.get(body['url'])  // no host/IP validation"],
        good_patterns=["allowlist of permitted hosts/schemes, resolve and reject private/loopback/link-local IP ranges before fetching"],
        exceptions=["Fixed, developer-controlled URLs (not from request input) are not SSRF risk."],
        detection_hints=["outbound HTTP call whose target URL comes directly from request body/query/headers with no validation step before it"],
        fix_strategy="Validate the URL against an allowlist and reject internal/private IP ranges before making the outbound request.",
        production_impact="Prevents internal network/service exposure and cloud credential theft via metadata endpoints.",
        standards=[{"name": "CWE", "reference": "CWE-918 Server-Side Request Forgery"}],
        source_urls=["https://cwe.mitre.org/data/definitions/918.html"],
        content="Requires evidence the URL is user-controlled, not merely that an HTTP client is used.",
    ),
    KnowledgeRecord(
        rule_id="SEC-WEB-008",
        title="Normalize and contain user-influenced file paths",
        category="security",
        subcategory="path-traversal",
        language=["any"],
        framework=["any"],
        severity="high",
        description="File reads/writes built from user input must be normalized and checked to stay within an intended base directory.",
        why_it_matters="Without containment, sequences like '../../' let an attacker read or write files outside the intended directory.",
        bad_patterns=["open(base_dir + user_filename)", "fs.readFile(path.join(uploadsDir, req.params.name))  // no containment check"],
        good_patterns=["normalize the resolved path and verify it still starts with the intended base directory before use"],
        exceptions=["Filenames generated server-side (e.g. a UUID) rather than taken from user input are not at risk."],
        detection_hints=["file path built by concatenating/joining a base directory with a request parameter, with no post-join containment check"],
        fix_strategy="Resolve the final path and assert it is still inside the allowed base directory before opening it; reject otherwise.",
        production_impact="Prevents arbitrary file read/write/disclosure outside the intended storage directory.",
        standards=[{"name": "CWE", "reference": "CWE-22 Path Traversal"}],
        source_urls=["https://cwe.mitre.org/data/definitions/22.html"],
        content="This repo's own ZIP-extraction code already implements this containment pattern (see _is_unsafe_path) — use it as the reference implementation when suggesting a fix.",
    ),
    KnowledgeRecord(
        rule_id="SEC-WEB-009",
        title="Validate uploaded files before storing or serving them",
        category="security",
        subcategory="file-upload",
        language=["any"],
        framework=["any"],
        severity="high",
        description="Uploads need type/size validation, and the upload directory must not be directly executable/servable as application code.",
        why_it_matters="Unrestricted uploads allow oversized-payload DoS, and executable uploads served from a web-accessible path can lead to remote code execution.",
        bad_patterns=["saving req.file to a web-served directory with no extension/mimetype/size check"],
        good_patterns=["allowlist of accepted extensions/mimetypes, an explicit max size, storage outside the web root or behind a non-executable static handler"],
        exceptions=["Internal admin-only upload tools with a trusted, small user base are lower risk but still worth a note."],
        detection_hints=["upload handler with no size/type validation before writing the file to disk"],
        fix_strategy="Add an extension/mimetype allowlist, enforce a max size, and store uploads outside any directory that executes code.",
        production_impact="Prevents remote code execution and denial-of-service through uploaded files.",
        standards=[{"name": "OWASP", "reference": "OWASP File Upload Cheat Sheet"}],
        source_urls=["https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html"],
        content="Note: this repo's own project-ZIP upload path already enforces size/count/path limits — reuse it as the reference pattern.",
    ),
    KnowledgeRecord(
        rule_id="SEC-WEB-010",
        title="Configure standard security response headers",
        category="security",
        subcategory="headers",
        language=["any"],
        framework=["express", "fastapi", "django"],
        severity="medium",
        description="Apps should send security headers (CSP, X-Content-Type-Options, X-Frame-Options/frame-ancestors, HSTS on HTTPS) rather than framework defaults alone.",
        why_it_matters="Missing headers weaken defense-in-depth against clickjacking, MIME-sniffing, and XSS impact.",
        bad_patterns=["no security-header middleware present and no reverse-proxy-level header configuration"],
        good_patterns=["Express: helmet() middleware", "FastAPI/Starlette: a security-headers middleware or edge/proxy configuration", "Django: django.middleware.security.SecurityMiddleware settings"],
        exceptions=["If headers are demonstrably set at the CDN/reverse-proxy layer, the application code is not required to duplicate them — note this as insufficient evidence rather than a confirmed gap."],
        detection_hints=["no helmet/security-header middleware registered, and no reverse proxy/infra config visible in the repo"],
        fix_strategy="Add the framework-appropriate security-header middleware (Helmet for Express, a Starlette middleware for FastAPI, SecurityMiddleware settings for Django).",
        production_impact="Reduces attack surface for clickjacking, MIME-confusion, and downgrade attacks.",
        standards=[{"name": "OWASP", "reference": "OWASP Secure Headers Project"}],
        source_urls=["https://owasp.org/www-project-secure-headers/"],
        content="Treat as an optional production improvement, not a confirmed defect, when header configuration might live outside the repo (CDN/proxy).",
    ),
    KnowledgeRecord(
        rule_id="SEC-WEB-011",
        title="Do not combine wildcard CORS with credentials",
        category="security",
        subcategory="cors",
        language=["any"],
        framework=["express", "fastapi"],
        severity="high",
        description="Access-Control-Allow-Origin: * (or an unchecked reflected Origin) must never be paired with Access-Control-Allow-Credentials: true.",
        why_it_matters="That combination lets any website make authenticated cross-origin requests using the victim's cookies/credentials.",
        bad_patterns=["CORSMiddleware(allow_origins=['*'], allow_credentials=True)", "cors({origin: true, credentials: true})  // reflects any origin"],
        good_patterns=["explicit allowlist of trusted origins when credentials are allowed; wildcard origin only when credentials are false"],
        exceptions=["A public, credential-free API (no cookies/auth headers relied upon) can safely use a wildcard origin."],
        detection_hints=["CORS configuration with origin wildcard/reflection AND credentials enabled at the same time"],
        fix_strategy="Replace the wildcard with an explicit list of trusted origins wherever credentials are allowed.",
        production_impact="Prevents cross-origin sites from performing authenticated actions on behalf of a logged-in user.",
        standards=[{"name": "OWASP", "reference": "OWASP CORS misconfiguration guidance"}],
        source_urls=["https://owasp.org/www-community/attacks/CORS_OriginHeaderScrutiny"],
        content="This repo's own CORSMiddleware(allow_origins=['*']) in server/main.py is exactly this pattern if credentials/cookies are ever introduced — currently the API is token-based with no cookie auth, so it is not yet a confirmed issue, only worth flagging if cookie-based auth is added.",
    ),
    KnowledgeRecord(
        rule_id="SEC-WEB-012",
        title="Rate-limit authentication and other abuse-prone endpoints",
        category="security",
        subcategory="rate-limiting",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Login, password reset, signup, and OTP endpoints should be throttled per IP/account.",
        why_it_matters="Without throttling, these endpoints are vulnerable to credential-stuffing and brute-force attacks.",
        bad_patterns=["login/reset endpoint with no rate limiting anywhere in its middleware chain"],
        good_patterns=["per-IP and/or per-account rate limiting middleware on auth-sensitive routes; the repo's own services/rate_limit.py check_rate_limit is one working example"],
        exceptions=["A general application-wide rate limiter already covering the route satisfies this; don't require a second, endpoint-specific limiter."],
        detection_hints=["auth-related route (login/reset/otp) with no rate-limit middleware/check in its chain, while other routes do have one"],
        fix_strategy="Apply the project's existing rate-limiting mechanism to authentication-sensitive endpoints specifically.",
        production_impact="Slows down credential-stuffing and brute-force attacks significantly.",
        standards=[{"name": "OWASP", "reference": "OWASP Top 10 A07:2021 Identification and Authentication Failures"}],
        source_urls=["https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/"],
        content="Check whether a general rate limiter already covers /api/* before flagging — this repo's rate_limit_middleware applies broadly, so this rule mainly applies to auth-specific stricter thresholds.",
    ),
    KnowledgeRecord(
        rule_id="SEC-GEN-013",
        title="Avoid weak or broken cryptographic algorithms",
        category="security",
        subcategory="cryptography",
        language=["any"],
        framework=["any"],
        severity="high",
        description="MD5, SHA1, and DES/ECB should not be used for security purposes (integrity, signatures, encryption).",
        why_it_matters="These algorithms have known practical attacks; using them for security-relevant purposes provides false assurance.",
        bad_patterns=["hashlib.md5(data) used for a signature/integrity check", "AES in ECB mode", "DES/3DES for new encryption"],
        good_patterns=["SHA-256/SHA-3 for integrity, AES-GCM for encryption, well-maintained libraries over hand-rolled crypto"],
        exceptions=["MD5/SHA1 used purely as a non-security checksum (e.g. cache key, dedup key) is not a security defect."],
        detection_hints=["md5/sha1 used in an auth, signature, or token-generation context specifically"],
        fix_strategy="Swap to a modern algorithm (SHA-256+/AES-GCM) via a maintained crypto library.",
        production_impact="Prevents forgery/collision attacks against integrity and authentication mechanisms.",
        standards=[{"name": "CWE", "reference": "CWE-327 Use of a Broken or Risky Cryptographic Algorithm"}],
        source_urls=["https://cwe.mitre.org/data/definitions/327.html"],
        content="Check the usage context — md5 as a cache/dedup key is fine, md5 in an auth/signature path is not.",
    ),
    KnowledgeRecord(
        rule_id="SEC-SUPPLY-001",
        title="Pin dependencies and commit a lockfile",
        category="security",
        subcategory="supply-chain",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Dependency versions should be pinned (lockfile committed) rather than left floating, and known-vulnerable versions should not be pinned indefinitely.",
        why_it_matters="Floating versions make builds non-reproducible and can silently pull in a compromised or breaking release; unpatched known-CVE versions stay exploitable.",
        bad_patterns=["requirements.txt with no version pins at all", "package.json present with no committed package-lock.json/yarn.lock/pnpm-lock.yaml"],
        good_patterns=["pinned versions in requirements.txt, a committed lockfile, and a periodic dependency audit (pip-audit, npm audit) in CI"],
        exceptions=["Framework/library repos intentionally supporting a wide version range are exempt — this applies to deployable applications."],
        detection_hints=["package.json present without a matching lockfile in the repo", "requirements.txt entries with no version specifier"],
        fix_strategy="Commit the lockfile the package manager already generates, and add a dependency-audit step to CI.",
        production_impact="Prevents unreviewed dependency drift and unpatched known vulnerabilities from reaching production.",
        standards=[{"name": "General", "reference": "Supply-chain / reproducible builds best practice"}],
        source_urls=[],
        content="Confirm the lockfile is genuinely absent from the repo (not just unlisted) before flagging.",
    ),

    # ---- architecture ----
    KnowledgeRecord(
        rule_id="ARCH-GEN-002",
        title="Keep application instances stateless",
        category="architecture",
        subcategory="statelessness",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Request-relevant state (sessions, in-progress job status, rate-limit counters) should live in a shared store, not in an in-process variable/dict.",
        why_it_matters="In-memory state is lost on restart and diverges across instances, breaking correctness the moment the app runs behind a load balancer or scales beyond one instance.",
        bad_patterns=["a module-level dict/list used as a session or job-status store", "in-memory rate-limit counters with no shared backing store"],
        good_patterns=["Redis/database-backed session and counter storage shared across instances"],
        exceptions=["A single-instance deployment with no near-term scaling plan can defer this — flag as an optional improvement, not a confirmed defect, unless the project already shows multi-instance/load-balancer configuration."],
        detection_hints=["module-level mutable dict/list used to track per-user or per-job state across requests"],
        fix_strategy="Move the state to a shared store (Redis, database) so any instance can serve any request.",
        production_impact="Enables horizontal scaling and prevents state loss/divergence across restarts and instances.",
        standards=[{"name": "General", "reference": "12-Factor App: Processes"}],
        source_urls=["https://12factor.net/processes"],
        content="This repo's own server/services/rate_limit.py in-memory limiter is an example of this exact pattern — worth citing as evidence when this rule fires here.",
    ),
    KnowledgeRecord(
        rule_id="ARCH-GEN-003",
        title="Externalize environment-specific configuration",
        category="architecture",
        subcategory="configuration",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="URLs, ports, feature flags, and other environment-specific values should come from environment variables/config, not literals in code.",
        why_it_matters="Hardcoded environment values force code changes to move between dev/staging/prod and risk shipping the wrong target by accident.",
        bad_patterns=["const API_URL = 'https://prod.example.com'  // hardcoded, no env override", "DEBUG = True hardcoded in a shared settings file"],
        good_patterns=["os.getenv/process.env-backed configuration with sensible defaults, documented in .env.example"],
        exceptions=["True constants that never vary by environment (e.g. a fixed public API version string) are not configuration."],
        detection_hints=["environment-looking value (host, port, flag) assigned as a literal rather than read from env/config"],
        fix_strategy="Move the value into environment variables or a config module already used elsewhere in the project.",
        production_impact="Prevents environment-mismatch incidents and makes the same build promotable across environments.",
        standards=[{"name": "General", "reference": "12-Factor App: Config"}],
        source_urls=["https://12factor.net/config"],
        content="Only flag values that plausibly differ between environments — not every string literal.",
    ),
    KnowledgeRecord(
        rule_id="ARCH-GEN-004",
        title="Avoid circular and overly tight coupling between modules",
        category="architecture",
        subcategory="coupling",
        language=["any"],
        framework=["any"],
        severity="low",
        description="Modules that import each other in a cycle, or reach deep into another module's internals, are hard to test and change in isolation.",
        why_it_matters="Circular imports cause fragile load-order bugs; deep coupling means a change in one module ripples unpredictably into unrelated ones.",
        bad_patterns=["module A imports module B and module B imports module A", "service directly manipulates another service's private/internal state instead of calling its public interface"],
        good_patterns=["a shared module/interface both depend on, or dependency inversion so the cycle is broken", "modules interact only through public functions/classes"],
        exceptions=["Small, intentional two-file cycles resolved with local imports are a pragmatic pattern in some codebases and not automatically a defect."],
        detection_hints=["import graph shows a cycle between two or more project-internal files"],
        fix_strategy="Extract the shared piece both modules need into a third module, or invert the dependency direction.",
        production_impact="Improves testability and reduces the blast radius of future changes.",
        standards=[{"name": "General", "reference": "Dependency inversion / acyclic dependencies principle"}],
        source_urls=[],
        content="Use the repository's own import graph (build_import_graph) as evidence — do not guess coupling from file names alone.",
    ),

    # ---- api design ----
    KnowledgeRecord(
        rule_id="API-GEN-002",
        title="Paginate endpoints that return collections",
        category="api_design",
        subcategory="pagination",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="List endpoints should support limit/offset or cursor-based pagination rather than returning the entire collection.",
        why_it_matters="Unbounded list responses grow without limit as data grows, causing large payloads, slow queries, and memory pressure.",
        bad_patterns=["return list(db.collection.find({}))  // no limit anywhere", "GET /items returns every row with no page/limit params"],
        good_patterns=["limit/offset or cursor query params enforced with a sane default and max, reflected in the DB query"],
        exceptions=["Small, inherently bounded collections (e.g. a fixed enum of categories) don't need pagination."],
        detection_hints=["a list/collection endpoint whose DB query has no .limit()/LIMIT and no page/cursor parameter"],
        fix_strategy="Add limit/offset or cursor-based pagination with a bounded default and maximum page size.",
        production_impact="Keeps response size and query cost bounded as the underlying data grows.",
        standards=[{"name": "General", "reference": "REST API pagination best practice"}],
        source_urls=[],
        content="Only applies to endpoints returning an open-ended collection, not fixed-size responses.",
    ),
    KnowledgeRecord(
        rule_id="API-GEN-003",
        title="Version the API before making breaking changes",
        category="api_design",
        subcategory="versioning",
        language=["any"],
        framework=["any"],
        severity="low",
        description="Breaking changes to a public endpoint's request/response shape should go through a version path/header rather than mutating the existing contract in place.",
        why_it_matters="Changing a live endpoint's shape breaks existing clients with no migration path.",
        bad_patterns=["removing/renaming a response field on an existing, already-consumed endpoint with no version bump"],
        good_patterns=["/api/v2/... or an Accept/version header for breaking changes, while /v1 keeps working"],
        exceptions=["Purely additive changes (new optional field) are backward compatible and don't need a version bump."],
        detection_hints=["evidence of a breaking shape change to an endpoint already used by the existing frontend"],
        fix_strategy="Introduce a new version path/header for the breaking change and keep the old contract available during migration.",
        production_impact="Prevents silent client breakage during API evolution.",
        standards=[{"name": "General", "reference": "REST API versioning best practice"}],
        source_urls=[],
        content="Requires evidence of an actual breaking change, not just any API evolution.",
    ),
    KnowledgeRecord(
        rule_id="API-GEN-004",
        title="Make retried mutating requests idempotent",
        category="api_design",
        subcategory="idempotency",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Endpoints that create side effects (orders, payments, emails) should support an idempotency key or otherwise be safe to retry.",
        why_it_matters="Network retries are inevitable; without idempotency a client retry after a timeout can duplicate an order, charge, or email.",
        bad_patterns=["POST /orders creates a new row unconditionally with no dedup/idempotency key"],
        good_patterns=["accept a client-supplied idempotency key and dedupe on it before performing the side effect"],
        exceptions=["Read-only or naturally idempotent endpoints (PUT-by-id full replace) don't need this."],
        detection_hints=["a payment/order/notification-creating POST endpoint with no idempotency key or dedup check"],
        fix_strategy="Accept and enforce an idempotency key (or a natural dedup key) before performing the side-effecting write.",
        production_impact="Prevents duplicate charges, orders, or notifications from client/network retries.",
        standards=[{"name": "General", "reference": "Idempotency key pattern (Stripe API design)"}],
        source_urls=[],
        content="Only applies to endpoints with a real side effect worth deduplicating, not to every POST.",
    ),
    KnowledgeRecord(
        rule_id="API-GEN-005",
        title="Enforce a maximum request payload size",
        category="api_design",
        subcategory="limits",
        language=["any"],
        framework=["express", "fastapi"],
        severity="medium",
        description="The server should reject oversized request bodies rather than accepting unbounded input.",
        why_it_matters="Without a limit, a client can send an arbitrarily large body and exhaust server memory or bandwidth (a simple DoS vector).",
        bad_patterns=["no body-size limit configured on the framework/server (default unlimited or very large)"],
        good_patterns=["explicit body-size limit configured (express.json({limit: '1mb'}), FastAPI/Starlette request size middleware or reverse-proxy limit)"],
        exceptions=["File-upload endpoints intentionally accepting large bodies should have their own explicit, deliberate limit instead of a blanket small one — this repo's MAX_ZIP_SIZE is exactly that pattern."],
        detection_hints=["no request-size limit configured anywhere in the app or documented at the reverse-proxy layer"],
        fix_strategy="Set an explicit request body size limit appropriate to the endpoint (small for JSON APIs, larger and deliberate for uploads).",
        production_impact="Bounds memory/bandwidth usage per request and reduces DoS exposure.",
        standards=[{"name": "General", "reference": "API resource-consumption limits best practice"}],
        source_urls=[],
        content="This repo already does this correctly for ZIP upload (MAX_ZIP_SIZE); this rule is about the general JSON API surface, not that path.",
    ),
    KnowledgeRecord(
        rule_id="API-GEN-006",
        title="Never return raw stack traces or internal errors to clients",
        category="api_design",
        subcategory="error-handling",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Error responses should be structured and generic to the client; full exception text/stack traces belong only in server-side logs.",
        why_it_matters="Raw exception text can leak file paths, library versions, query fragments, or internal architecture useful to an attacker.",
        bad_patterns=["except Exception as e: return {'error': str(e)}  // raw exception text returned to caller", "unhandled exception whose default framework error page includes a stack trace in production"],
        good_patterns=["catch and log the real error server-side; return a generic structured error body to the client (this repo's routers already do this in most places, e.g. _ERROR_RESPONSE constants)"],
        exceptions=["Development-mode-only detailed errors, clearly gated off in production, are acceptable."],
        detection_hints=["an except/catch block that serializes the exception object/message directly into the HTTP response body"],
        fix_strategy="Log the full exception server-side and replace the client-facing body with a generic, structured error message.",
        production_impact="Prevents information disclosure that helps attackers map the application's internals.",
        standards=[{"name": "OWASP", "reference": "OWASP API Security Top 10 - API8:2023 Security Misconfiguration"}],
        source_urls=["https://owasp.org/API-Security/editions/2023/en/0xa8-security-misconfiguration/"],
        content="This repo's routers/projects.py mostly does this correctly already (generic _ERROR_RESPONSE constants) — check each handler individually rather than assuming.",
    ),
    KnowledgeRecord(
        rule_id="API-GEN-007",
        title="Set timeouts on outbound HTTP/network calls",
        category="api_design",
        subcategory="reliability",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Every outbound call to another service (HTTP client, DB driver, cache client) should have an explicit timeout.",
        why_it_matters="Without a timeout, a slow/hanging downstream dependency can hold a request thread/connection indefinitely, exhausting the pool and taking the whole app down.",
        bad_patterns=["requests.get(url)  // no timeout kwarg", "httpx.AsyncClient() with no timeout configured", "axios.get(url)  // relies on default (often none/very long)"],
        good_patterns=["explicit timeout on every outbound call, matching this repo's own httpx.AsyncClient(timeout=30) pattern in knowledge/embeddings.py"],
        exceptions=["Long-lived intentional streaming connections (websockets, SSE) are a different pattern and shouldn't be flagged for lacking a request timeout."],
        detection_hints=["outbound HTTP client call with no timeout parameter set, in a file that otherwise shows the project does set timeouts elsewhere"],
        fix_strategy="Add an explicit, reasonable timeout to the outbound call, consistent with timeouts already used elsewhere in the project.",
        production_impact="Prevents a single slow dependency from cascading into full application unavailability.",
        standards=[{"name": "General", "reference": "Release It! (Nygard) - stability patterns: timeouts"}],
        source_urls=[],
        content="This repo already sets timeout=30 on its own outbound GitHub/embedding calls — use that as the in-project reference pattern for a fix.",
    ),

    # ---- database ----
    KnowledgeRecord(
        rule_id="DB-GEN-001",
        title="Index fields used in frequent filters and sorts",
        category="database",
        subcategory="indexing",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Fields regularly used in query filters, sorts, or joins should have a matching index (single-field or compound, in query-field order).",
        why_it_matters="Without an index, the database falls back to a collection/table scan, which grows linearly worse as data grows.",
        bad_patterns=["frequent query filters/sorts on a field with no corresponding index defined anywhere in the schema/migrations"],
        good_patterns=["an index (or compound index matching the query's filter+sort fields) covering the hot query path"],
        exceptions=["Small, rarely-queried, or admin-only collections/tables don't need index optimization."],
        detection_hints=["a query filtering/sorting on a field that no create_index/migration/schema definition in the repo covers"],
        fix_strategy="Add an index (compound if multiple fields are filtered/sorted together, in the order the query uses them) for the hot query path.",
        production_impact="Keeps query latency roughly constant as the collection/table grows instead of degrading linearly.",
        standards=[{"name": "General", "reference": "MongoDB/SQL indexing best practice"}],
        source_urls=[],
        content="Requires evidence of both the query pattern and the absence of a matching index in the repo's schema/migration/index-creation code.",
    ),
    KnowledgeRecord(
        rule_id="DB-GEN-002",
        title="Avoid N+1 query patterns",
        category="database",
        subcategory="query-patterns",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="A loop that issues one query per iteration should instead use a single batched query, a join, or an `$in`/`IN` lookup.",
        why_it_matters="N+1 queries turn a single logical operation into N+1 round trips to the database, dominating request latency as N grows.",
        bad_patterns=["for item in items: db.query(SomeModel).filter_by(id=item.ref_id).first()  // one query per loop iteration"],
        good_patterns=["a single batched query using IN/$in over all needed ids, or a join/populate/prefetch"],
        exceptions=["Loops over a small, fixed, known-bounded set (e.g. 2-3 config lookups) are not a meaningful N+1 concern."],
        detection_hints=["a database call sitting inside a for/while loop whose iteration count is driven by another collection"],
        fix_strategy="Replace the per-iteration query with a single batched query keyed on all needed ids at once.",
        production_impact="Turns O(N) database round trips into O(1), a major latency and DB-load improvement at scale.",
        standards=[{"name": "General", "reference": "N+1 query anti-pattern"}],
        source_urls=[],
        content="Requires seeing the actual loop body with a query call inside it — do not infer from a function name alone.",
    ),
    KnowledgeRecord(
        rule_id="DB-GEN-003",
        title="Reuse a connection pool instead of connecting per request",
        category="database",
        subcategory="connection-management",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Database clients should be created once (a pool) at startup and reused, not instantiated fresh inside each request handler.",
        why_it_matters="Opening a new connection per request adds latency and can exhaust the database's max-connections limit under load.",
        bad_patterns=["def handler(): client = MongoClient(...)  // new client created inside the request path"],
        good_patterns=["a module-level client/pool created once at import/startup and reused by every request — this repo's own db/mongo.py does this correctly"],
        exceptions=["Short-lived scripts/one-off tools that run once and exit are fine creating their own single connection."],
        detection_hints=["a database client constructor call located inside a request handler function rather than at module import time"],
        fix_strategy="Move the client construction to module import time (or an app-startup hook) and reuse it across requests.",
        production_impact="Removes per-request connection-setup latency and prevents connection-limit exhaustion under load.",
        standards=[{"name": "General", "reference": "Connection pooling best practice"}],
        source_urls=[],
        content="This repo's db/mongo.py already does this correctly (module-level AsyncIOMotorClient) — use it as the reference pattern when this rule fires elsewhere.",
    ),
    KnowledgeRecord(
        rule_id="DB-GEN-004",
        title="Wrap related multi-step writes in a transaction",
        category="database",
        subcategory="transactions",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="When two or more writes must succeed or fail together (e.g. debit one record, credit another), they should run inside a database transaction.",
        why_it_matters="Without a transaction, a crash or error between the two writes leaves the data in a partially-updated, inconsistent state.",
        bad_patterns=["two related db.update_one/UPDATE calls in sequence with no transaction/session wrapping them"],
        good_patterns=["a database session/transaction (client.start_session()+with_transaction, or a SQL BEGIN/COMMIT) wrapping the related writes"],
        exceptions=["A single independent write, or writes that are naturally safe to apply out of order, don't need a transaction."],
        detection_hints=["two or more related, sequential write calls affecting different documents/rows with no session/transaction wrapping them"],
        fix_strategy="Wrap the related writes in a database transaction/session so they commit or roll back together.",
        production_impact="Prevents partial-write data corruption when a related multi-step operation fails midway.",
        standards=[{"name": "General", "reference": "ACID transaction best practice"}],
        source_urls=[],
        content="Only applies when the writes are genuinely related/dependent — independent writes to unrelated data don't need this.",
    ),
    KnowledgeRecord(
        rule_id="DB-GEN-005",
        title="Track schema changes as versioned migrations",
        category="database",
        subcategory="migrations",
        language=["any"],
        framework=["any"],
        severity="low",
        description="Schema/index changes should be captured in versioned migration files in the repo, not applied ad hoc against a live database.",
        why_it_matters="Undocumented manual schema changes can't be reproduced in a new environment and aren't reviewable or reversible.",
        bad_patterns=["schema/index changes referenced only in chat/documentation, no migration file in the repo"],
        good_patterns=["a migrations/ directory (Alembic, Django migrations, or an explicit index-creation script like this repo's knowledge/ingest.py) checked into version control"],
        exceptions=["Schemaless-by-design collections that only ever gain optional fields have looser requirements here."],
        detection_hints=["evidence of schema/index changes with no corresponding versioned migration script in the repo"],
        fix_strategy="Capture the schema/index change as a versioned, rerunnable script checked into the repo, following the project's existing pattern.",
        production_impact="Makes schema state reproducible, reviewable, and safe to apply consistently across environments.",
        standards=[{"name": "General", "reference": "Database migration best practice"}],
        source_urls=[],
        content="This repo's knowledge/ingest.py index-creation code is a reasonable in-project example of a rerunnable, versioned setup script.",
    ),

    # ---- performance ----
    KnowledgeRecord(
        rule_id="PERF-GEN-002",
        title="Cache genuinely repeated expensive work",
        category="performance",
        subcategory="caching",
        language=["any"],
        framework=["any"],
        severity="low",
        description="When the same expensive computation or query is demonstrably repeated for the same input, a cache reduces redundant work.",
        why_it_matters="Repeating expensive work (external calls, heavy computation, unchanged query results) wastes latency and resources on every request.",
        bad_patterns=["the same expensive external call or computation re-executed for identical input within a short window, with no cache anywhere"],
        good_patterns=["an in-process cache (functools.lru_cache) for small/simple cases, or Redis/shared cache for multi-instance deployments — matched to the actual scale of the problem"],
        exceptions=["Do NOT flag the mere absence of Redis/a cache layer as a defect. Only flag when the code shows a specific, repeated, expensive operation with unchanging results — not as a generic 'add caching' recommendation."],
        detection_hints=["the same expensive call/query executed multiple times for input that doesn't change within the request/session lifetime"],
        fix_strategy="Add a cache scoped to the actual repetition observed — an in-process cache is often sufficient before reaching for a new infrastructure dependency.",
        production_impact="Reduces redundant latency and load from work that produces the same result repeatedly.",
        standards=[{"name": "General", "reference": "Caching best practice"}],
        source_urls=[],
        content="This is a CONFIRMED-PROBLEM rule only with direct evidence of repetition — otherwise treat as an OPTIONAL PRODUCTION IMPROVEMENT or INSUFFICIENT EVIDENCE, never a generic 'add Redis' finding.",
    ),
    KnowledgeRecord(
        rule_id="PERF-GEN-003",
        title="Set HTTP caching headers for cacheable responses",
        category="performance",
        subcategory="http-caching",
        language=["any"],
        framework=["any"],
        severity="low",
        description="Static or infrequently-changing responses should carry Cache-Control/ETag so clients and CDNs can avoid refetching unchanged data.",
        why_it_matters="Without cache headers, every client refetches unchanged content on every request, wasting bandwidth and server capacity.",
        bad_patterns=["a static/rarely-changing endpoint response with no Cache-Control/ETag header set"],
        good_patterns=["Cache-Control with an appropriate max-age, and/or an ETag for conditional requests"],
        exceptions=["Personalized or frequently-changing data (per-user dashboards, live counters) should not be cached and this rule doesn't apply."],
        detection_hints=["a response for genuinely static/shared content with no cache-related header set anywhere in the handler"],
        fix_strategy="Add Cache-Control (and ETag where useful) sized to how often the underlying content actually changes.",
        production_impact="Reduces bandwidth and server load for content that doesn't need to be refetched every time.",
        standards=[{"name": "MDN", "reference": "HTTP Caching"}],
        source_urls=["https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching"],
        content="Only applies to genuinely cacheable, non-personalized content — this is an OPTIONAL PRODUCTION IMPROVEMENT, not a security/correctness defect.",
    ),
    KnowledgeRecord(
        rule_id="PERF-GEN-004",
        title="Enable response compression for large payloads",
        category="performance",
        subcategory="compression",
        language=["any"],
        framework=["express", "fastapi"],
        severity="low",
        description="Large JSON/text responses should be served with gzip/brotli compression.",
        why_it_matters="Uncompressed large payloads waste bandwidth and slow down clients, especially on constrained networks.",
        bad_patterns=["no compression middleware configured (compression()/GZipMiddleware) despite large JSON/text responses"],
        good_patterns=["Express: compression() middleware. FastAPI/Starlette: GZipMiddleware.", "already handled at the CDN/reverse-proxy layer counts as satisfied"],
        exceptions=["Small responses, or apps demonstrably behind a CDN/proxy that already compresses, don't need this at the app layer — note as insufficient evidence rather than a confirmed gap if proxy config isn't visible in the repo."],
        detection_hints=["no compression middleware present and response payloads are demonstrably large (bulk list/data endpoints)"],
        fix_strategy="Add the framework's compression middleware, sized to actual response payload sizes observed.",
        production_impact="Reduces bandwidth usage and improves perceived latency on constrained networks.",
        standards=[{"name": "General", "reference": "HTTP compression best practice"}],
        source_urls=[],
        content="Optional production improvement — do not treat as a confirmed defect when payload sizes are small or proxy-level compression can't be ruled out.",
    ),

    # ---- background work ----
    KnowledgeRecord(
        rule_id="BG-GEN-001",
        title="Retry transient external-call failures with backoff",
        category="reliability",
        subcategory="retries",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Calls to external/network dependencies that can fail transiently should retry with exponential backoff (bounded attempts), not fail immediately or retry in a tight loop.",
        why_it_matters="A single transient failure without retry causes unnecessary user-facing errors; retrying without backoff can hammer an already-struggling dependency and make things worse.",
        bad_patterns=["a single external call attempt with no retry on timeout/connection error", "an unbounded while-True retry loop with no backoff or max-attempts"],
        good_patterns=["bounded retries with exponential backoff — this repo's own services/groq_client.py MAX_ATTEMPTS=3 pattern is a working in-project example"],
        exceptions=["Idempotency-unsafe operations (side effects that aren't safe to duplicate) need care before adding a blind retry — pair with BG-GEN-002."],
        detection_hints=["outbound call with no retry logic at all, or a retry loop with no bound on attempts and no backoff delay"],
        fix_strategy="Add bounded retries with exponential backoff, following the pattern already used in the project's own Groq client if present.",
        production_impact="Improves resilience to transient network/dependency failures without amplifying load during an outage.",
        standards=[{"name": "General", "reference": "Exponential backoff and retry best practice"}],
        source_urls=[],
        content="This repo's own services/groq_client.py already implements bounded retry with key rotation, but without an explicit backoff delay between attempts — cite that gap specifically if evaluating that file.",
    ),
    KnowledgeRecord(
        rule_id="BG-GEN-002",
        title="Design background job handlers to be safe to run twice",
        category="reliability",
        subcategory="idempotent-jobs",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Queue/worker job handlers should tolerate at-least-once delivery — running the same message twice must not cause duplicate side effects.",
        why_it_matters="Most queues guarantee at-least-once delivery; a handler that isn't idempotent will occasionally double-send an email, double-charge, or double-write on redelivery.",
        bad_patterns=["a job handler that performs a side effect (send email, charge card, insert row) with no dedup/idempotency check against reprocessing the same message"],
        good_patterns=["dedup key stored per processed message id, or a naturally idempotent write (upsert keyed on a stable id) instead of an unconditional insert"],
        exceptions=["Purely read-only or naturally idempotent jobs (recompute-and-overwrite the same value) don't need explicit dedup."],
        detection_hints=["a queue/worker consumer whose handler body performs a side effect with no message-id dedup check"],
        fix_strategy="Track processed message ids (or use an upsert keyed on a stable identifier) so redelivery doesn't duplicate the side effect.",
        production_impact="Prevents duplicate emails, charges, or writes when the queue redelivers a message.",
        standards=[{"name": "General", "reference": "Idempotent consumer pattern"}],
        source_urls=[],
        content="Only applies to projects that actually use a queue/worker system — do not require one to exist.",
    ),

    # ---- reliability / observability ----
    KnowledgeRecord(
        rule_id="REL-GEN-001",
        title="Shut down gracefully on SIGTERM",
        category="reliability",
        subcategory="graceful-shutdown",
        language=["any"],
        framework=["fastapi", "express"],
        severity="low",
        description="The process should finish in-flight requests and close connections cleanly on shutdown signal, rather than dying mid-request.",
        why_it_matters="Without graceful shutdown, deploys/restarts abruptly cut off in-flight requests and can leave connections or transactions in a bad state.",
        bad_patterns=["no shutdown handler; the process just exits on SIGTERM with in-flight requests dropped"],
        good_patterns=["FastAPI @app.on_event('shutdown') / lifespan handler closing DB connections; Express server.close() draining connections on SIGTERM"],
        exceptions=["Simple internal scripts/one-off tools don't need this — it matters for long-running request-serving processes."],
        detection_hints=["no shutdown/lifespan handler present in a long-running server process"],
        fix_strategy="Add a shutdown handler that stops accepting new requests, drains in-flight ones, and closes DB/queue connections.",
        production_impact="Prevents dropped requests and connection leaks during deploys and restarts.",
        standards=[{"name": "General", "reference": "12-Factor App: Disposability"}],
        source_urls=["https://12factor.net/disposability"],
        content="Optional production improvement for most hackathon-stage projects — flag as LIKELY PROBLEM only if the project is clearly targeting production deployment.",
    ),
    KnowledgeRecord(
        rule_id="REL-GEN-002",
        title="Expose a health-check endpoint",
        category="reliability",
        subcategory="health-checks",
        language=["any"],
        framework=["any"],
        severity="low",
        description="A lightweight /health (and ideally separate /ready) endpoint lets an orchestrator/load balancer know the process is alive and able to serve traffic.",
        why_it_matters="Without a health check, an orchestrator can't detect a hung/broken instance and keeps routing traffic to it.",
        bad_patterns=["no /health or equivalent endpoint anywhere in the router set"],
        good_patterns=["a simple /health returning 200 when the process is up, and ideally a /ready that checks dependencies (DB reachable) are actually available"],
        exceptions=["None — this is cheap to add to essentially any deployed service."],
        detection_hints=["no health-check route registered anywhere in the app"],
        fix_strategy="Add a /health endpoint; if orchestrated with readiness probes, add a /ready that checks critical dependencies.",
        production_impact="Lets the deployment platform detect and route around unhealthy instances automatically.",
        standards=[{"name": "General", "reference": "Kubernetes/orchestration liveness & readiness probes"}],
        source_urls=[],
        content="This repo's server/main.py already has @app.get('/health') — treat this rule as satisfied here; use it as a positive example when auditing other projects.",
    ),
    KnowledgeRecord(
        rule_id="REL-GEN-003",
        title="Isolate failures from unreliable downstream dependencies",
        category="reliability",
        subcategory="failure-isolation",
        language=["any"],
        framework=["any"],
        severity="low",
        description="Repeated calls to a downstream dependency that is currently failing should short-circuit (circuit breaker) instead of retrying indefinitely and piling up latency.",
        why_it_matters="Without isolation, a failing downstream dependency can exhaust the caller's own resources (threads, connections, timeouts) and take down an otherwise-healthy service.",
        bad_patterns=["every request re-attempts a call to a dependency that has been failing continuously, with no short-circuit"],
        good_patterns=["a circuit-breaker pattern (or, at minimum, this repo's own per-key cooldown pattern in groq_client.py) that stops hammering a known-bad dependency for a cooldown period"],
        exceptions=["Low-traffic internal tools where the blast radius of a hung call is small can defer this."],
        detection_hints=["repeated calls to a dependency with a known recent failure and no cooldown/circuit-breaker logic"],
        fix_strategy="Add a circuit-breaker or cooldown so repeated calls to a currently-failing dependency back off instead of piling up.",
        production_impact="Contains the blast radius of a downstream outage instead of letting it cascade.",
        standards=[{"name": "General", "reference": "Release It! (Nygard) - Circuit Breaker pattern"}],
        source_urls=[],
        content="This repo's groq_client.py per-key cooldown on 401/429 is a partial working example of this pattern already.",
    ),
    KnowledgeRecord(
        rule_id="OBS-GEN-001",
        title="Log without leaking secrets or full sensitive payloads",
        category="reliability",
        subcategory="observability",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="Structured logs are valuable for debugging, but must not include passwords, tokens, API keys, or full sensitive request/response bodies.",
        why_it_matters="Logs are often less tightly access-controlled than the primary database, and commonly shipped to third-party log aggregators — secrets logged there are a real leak vector.",
        bad_patterns=["print(request.headers)  // includes Authorization header", "logging the full request body of an auth/payment endpoint unredacted"],
        good_patterns=["redact/omit Authorization, cookies, and password/token fields before logging; log identifiers, not full payloads, for sensitive routes"],
        exceptions=["Logging structural metadata (status code, path, duration, non-sensitive fields) is fine and encouraged."],
        detection_hints=["log/print statement that includes the whole request/response object or headers on an auth-sensitive route"],
        fix_strategy="Redact sensitive headers/fields before logging, or log only the specific non-sensitive fields needed for debugging.",
        production_impact="Prevents secrets and personal data from leaking into log storage/aggregation systems.",
        standards=[{"name": "OWASP", "reference": "OWASP Logging Cheat Sheet"}],
        source_urls=["https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html"],
        content="Check what's actually being logged, not just that logging exists — logging itself is good practice, leaking secrets in it is the defect.",
    ),
    KnowledgeRecord(
        rule_id="OBS-GEN-002",
        title="Propagate a request/correlation id through logs",
        category="reliability",
        subcategory="observability",
        language=["any"],
        framework=["any"],
        severity="low",
        description="Each request should carry a correlation id (generated or forwarded) included in every log line it produces, so a single request's logs can be traced end to end.",
        why_it_matters="Without a correlation id, reconstructing what happened for one specific failing request out of interleaved concurrent logs is very difficult.",
        bad_patterns=["log lines with no request/correlation id, indistinguishable from concurrent requests"],
        good_patterns=["a request-id middleware that generates/forwards an id and includes it in every log line for that request"],
        exceptions=["Single-request scripts/tools with no concurrency don't need this."],
        detection_hints=["no request-id/correlation-id middleware or logging context anywhere in the request-handling path"],
        fix_strategy="Add request-id middleware and include the id in every log statement for that request's lifecycle.",
        production_impact="Makes debugging a specific failing request in production tractable instead of guesswork.",
        standards=[{"name": "General", "reference": "Distributed tracing / correlation id best practice"}],
        source_urls=[],
        content="Optional production improvement — most valuable once the app has real concurrent production traffic.",
    ),

    # ---- devops / testing ----
    KnowledgeRecord(
        rule_id="DEVOPS-GEN-001",
        title="Run the test suite in CI before merge",
        category="testing",
        subcategory="ci",
        language=["any"],
        framework=["any"],
        severity="medium",
        description="A CI workflow should run lint and the test suite on every PR/push, not rely on developers running tests manually.",
        why_it_matters="Without CI enforcement, a broken change can merge and reach production before anyone notices the failing tests.",
        bad_patterns=["a tests/ directory exists but no .github/workflows (or equivalent CI config) runs it automatically"],
        good_patterns=["a CI workflow file that installs dependencies, runs lint, and runs the test suite on every push/PR"],
        exceptions=["Solo prototype/hackathon-stage repos may reasonably defer this — note as an optional improvement, not a confirmed defect, at that stage."],
        detection_hints=["tests exist in the repo but no CI workflow file (.github/workflows, .gitlab-ci.yml, etc.) references running them"],
        fix_strategy="Add a CI workflow that installs dependencies and runs the existing test suite on every push/PR.",
        production_impact="Catches regressions before they merge instead of after they reach production.",
        standards=[{"name": "General", "reference": "Continuous Integration best practice"}],
        source_urls=[],
        content="Check for tests first — recommending CI when there are zero tests to run is not useful; pair with TEST-01 from the deterministic standards set.",
    ),
    KnowledgeRecord(
        rule_id="DEVOPS-GEN-002",
        title="Support zero-downtime deploys with a rollback path",
        category="production_readiness",
        subcategory="deployment",
        language=["any"],
        framework=["any"],
        severity="low",
        description="Deployments should avoid a hard-cutover window with no traffic served, and there should be a documented/scripted way to roll back a bad release.",
        why_it_matters="A hard-cutover deploy causes a visible outage on every release; with no rollback path, a bad release stays live longer than necessary while a fix is prepared.",
        bad_patterns=["single-instance deploy that stops the old process before the new one is ready, with no documented rollback procedure"],
        good_patterns=["rolling/blue-green/canary deploy support from the hosting platform, plus a documented or scripted rollback (redeploy previous image/tag)"],
        exceptions=["Early-stage/internal tools with acceptable brief downtime can defer this — treat as an optional improvement, not a defect, unless the project is clearly production-critical."],
        detection_hints=["no deployment configuration showing rolling/blue-green support, and no documented rollback procedure in the repo"],
        fix_strategy="Use the hosting platform's rolling/blue-green deploy feature where available, and document the rollback command/procedure.",
        production_impact="Reduces deploy-time downtime and shortens recovery time from a bad release.",
        standards=[{"name": "General", "reference": "12-Factor App: Disposability / zero-downtime deploys"}],
        source_urls=["https://12factor.net/disposability"],
        content="This is largely a platform-configuration concern (Render/Vercel/K8s) that may not be visible from application source at all — mark INSUFFICIENT EVIDENCE rather than guessing when deployment config isn't in the repo.",
    ),

    # ---- frontend ----
    KnowledgeRecord(
        rule_id="FE-GEN-001",
        title="Avoid client-side XSS via unsanitized HTML injection",
        category="architecture",
        subcategory="frontend-security",
        language=["javascript", "typescript"],
        framework=["react"],
        severity="high",
        description="dangerouslySetInnerHTML (React) or direct .innerHTML assignment with content derived from user/API data must be sanitized first.",
        why_it_matters="Rendering unsanitized content as HTML lets injected script execute in another user's browser session.",
        bad_patterns=["<div dangerouslySetInnerHTML={{__html: apiResponse.bio}} />  // unsanitized user-controlled content"],
        good_patterns=["render as plain text/JSX by default; sanitize with DOMPurify before any raw-HTML rendering of user/API-derived content"],
        exceptions=["Content that is fully static/developer-authored (never derived from user input or an API response) is not at risk."],
        detection_hints=["dangerouslySetInnerHTML/innerHTML fed by a variable that traces back to an API response or user input"],
        fix_strategy="Sanitize the HTML with an allowlist-based library (DOMPurify) before rendering, or render as text instead.",
        production_impact="Prevents client-side script injection and session/token theft via the frontend.",
        standards=[{"name": "OWASP", "reference": "OWASP Top 10 A03:2021 Injection (XSS)"}],
        source_urls=["https://owasp.org/www-community/attacks/xss/"],
        content="Same underlying issue as SEC-WEB-005 but scoped specifically to frontend rendering code for this repo's React client.",
    ),
    KnowledgeRecord(
        rule_id="FE-GEN-002",
        title="Avoid storing auth tokens in localStorage/sessionStorage",
        category="architecture",
        subcategory="frontend-security",
        language=["javascript", "typescript"],
        framework=["react"],
        severity="medium",
        description="Access/refresh tokens stored in localStorage or sessionStorage are readable by any script running on the page, including injected XSS payloads.",
        why_it_matters="If an XSS vulnerability exists anywhere on the page, localStorage-stored tokens can be exfiltrated directly by the attacker's script.",
        bad_patterns=["localStorage.setItem('token', accessToken)", "sessionStorage.setItem('jwt', token)"],
        good_patterns=["store the token in an HttpOnly cookie set by the server (not readable by JS at all), or keep it in memory only for the session"],
        exceptions=["Non-sensitive, non-auth tokens (e.g. a public read-only API key already meant to be client-visible) are not at risk here."],
        detection_hints=["localStorage/sessionStorage.setItem call storing a value named token/jwt/auth/access_token/refresh_token"],
        fix_strategy="Move the token to an HttpOnly cookie set by the backend, or keep it in memory (React state/context) rather than persistent browser storage.",
        production_impact="Limits token exposure if an XSS vulnerability is ever introduced elsewhere on the page.",
        standards=[{"name": "OWASP", "reference": "OWASP JWT storage guidance"}],
        source_urls=["https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html"],
        content="Only applies to projects that actually implement token-based auth in the frontend.",
    ),
    KnowledgeRecord(
        rule_id="FE-GEN-003",
        title="Handle API failure, loading, and error states explicitly",
        category="architecture",
        subcategory="frontend-reliability",
        language=["javascript", "typescript"],
        framework=["react"],
        severity="low",
        description="Data-fetching components should render distinct loading/error/empty states, not assume every request succeeds.",
        why_it_matters="Without explicit error handling, a failed request leaves the user looking at a stuck spinner or a blank/broken UI with no explanation.",
        bad_patterns=["fetch/axios call in a component with no .catch/try-catch and no error state rendered"],
        good_patterns=["explicit loading/error/success state (or a data-fetching library like React Query that provides them) with a visible error message on failure"],
        exceptions=["Fire-and-forget analytics/tracking calls don't need user-facing error UI."],
        detection_hints=["a data-fetching call in a component with no catch handling and no error state ever rendered in the JSX"],
        fix_strategy="Add explicit loading/error state handling and render a clear message when a request fails.",
        production_impact="Prevents users from being stuck on a silent failure with no feedback or recovery path.",
        standards=[{"name": "General", "reference": "Frontend error/loading state best practice"}],
        source_urls=[],
        content="Check the actual component body for catch/error-state handling before flagging — many components already do this correctly.",
    ),
    KnowledgeRecord(
        rule_id="FE-GEN-004",
        title="Split and lazy-load large frontend bundles",
        category="performance",
        subcategory="bundle-size",
        language=["javascript", "typescript"],
        framework=["react"],
        severity="low",
        description="Large routes/components should be code-split and lazy-loaded rather than shipped in a single monolithic JS bundle.",
        why_it_matters="A single large bundle delays first paint/interactivity for every visitor, even ones who only need a small part of the app.",
        bad_patterns=["every route/page statically imported at the top level with no React.lazy/dynamic import anywhere in the app"],
        good_patterns=["React.lazy + Suspense (or the bundler's dynamic import()) for large/rarely-visited routes and heavy components (e.g. a code editor, a chart library)"],
        exceptions=["Small apps with a genuinely small total bundle don't need code-splitting — check actual bundle size before flagging, don't assume."],
        detection_hints=["large, rarely-used dependency (editor, charting library) imported statically at the top of the app instead of via React.lazy/dynamic import"],
        fix_strategy="Convert large/rarely-visited routes or heavy components to React.lazy + Suspense boundaries.",
        production_impact="Reduces initial bundle size and improves first-load performance.",
        standards=[{"name": "web.dev", "reference": "Code-splitting with React.lazy"}],
        source_urls=["https://web.dev/articles/code-splitting-suspense"],
        content="Requires evidence of an actually large dependency/bundle, not a generic recommendation for every React app.",
    ),
]


def _detector_record(
    rule_id: str,
    title: str,
    category: str,
    subcategory: str,
    languages: list[str],
    severity: str,
    bad_pattern: str,
    good_pattern: str,
    detection_hint: str,
    false_positive_guard: str,
    recommendation: str,
):
    return KnowledgeRecord(
        rule_id=rule_id,
        title=title,
        category=category,
        subcategory=subcategory,
        language=languages,
        framework=["any"],
        severity=severity,
        description=title,
        why_it_matters=f"{title} can create production security, correctness, reliability, or operability risk when the detector evidence is real.",
        bad_patterns=[bad_pattern],
        good_patterns=[good_pattern],
        exceptions=[false_positive_guard],
        detection_hints=[detection_hint],
        fix_strategy=recommendation,
        production_impact="Use the detector evidence as the source of truth; this knowledge record explains why the observed pattern matters and how to fix it safely.",
        standards=[{"name": "Code Master AI", "reference": f"detector:{rule_id}"}],
        source_urls=[],
        content=(
            f"Principle: {title}. Warning signal: {detection_hint}. "
            f"Failure signal: {bad_pattern}. Healthy signal: {good_pattern}. "
            f"False-positive guard: {false_positive_guard}. Recommendation: {recommendation}"
        ),
    )


KNOWLEDGE_RECORDS.extend(
    [
        _detector_record("os_system_call", "Avoid direct OS command execution APIs", "security", "command-injection", ["python"], "high", "os.system(request value)", "Use subprocess with argv list, shell=False, and allowlisted arguments.", "os.system/os.popen/commands.getoutput call", "Static admin scripts with fixed literal commands may be acceptable after review.", "Replace shell-string execution with fixed executable arguments and validation."),
        _detector_record("spawn_shell_true", "Avoid Node spawn with shell enabled", "security", "command-injection", ["javascript", "typescript"], "high", "child_process.spawn(cmd, args, { shell: true })", "Use spawn with shell:false and fixed executable/argument boundaries.", "spawn/spawnSync configured with shell:true", "Build scripts using only fixed literals are lower risk but still deserve review.", "Disable shell mode and validate every user-influenced argument."),
        _detector_record("nosql_untrusted_filter", "Do not pass request objects directly to NoSQL filters", "security", "nosql-injection", ["javascript", "typescript", "python"], "high", "User.find(req.body)", "Build an allowlisted filter from validated fields.", "find/update/delete call receives req.body/request.json directly", "Only fixed server-constructed filter objects are acceptable.", "Validate and allowlist filter fields before constructing the query."),
        _detector_record("unsafe_archive_extract", "Contain archive extraction paths", "security", "archive-extraction", ["javascript", "typescript", "python"], "high", "ZipFile(...).extractall(dest)", "Validate every member path stays under the intended extraction directory.", "extractall/extractAllTo without visible containment checks", "Trusted developer-only archives in one-off scripts are lower risk.", "Normalize member paths and reject traversal/absolute paths before extraction."),
        _detector_record("ssrf_untrusted_url", "Validate untrusted outbound request URLs", "security", "ssrf", ["javascript", "typescript", "python"], "high", "requests.get(request.args['url'])", "Allowlist hosts/schemes and block private/internal IP ranges.", "HTTP client URL comes directly from request input", "Fixed developer-controlled URLs are not SSRF evidence.", "Validate URL scheme, host, resolved IP range, and redirect behavior before making the request."),
        _detector_record("xss_unsafe_html_sink", "Avoid assigning untrusted data to HTML sinks", "security", "xss", ["javascript", "typescript"], "high", "element.innerHTML = req.body.html", "Render text or sanitize HTML with an allowlist sanitizer.", "innerHTML/outerHTML assignment from request/location/props/state", "Static developer-authored HTML is not user-controlled.", "Replace raw HTML assignment with text rendering or sanitize with DOMPurify."),
        _detector_record("react_dangerous_html", "Treat React dangerouslySetInnerHTML as a security boundary", "security", "frontend-xss", ["javascript", "typescript"], "medium", "dangerouslySetInnerHTML={{__html: html}}", "Only pass sanitized, trusted HTML into dangerouslySetInnerHTML.", "dangerouslySetInnerHTML usage", "Static CMS/admin-controlled HTML may be acceptable if sanitized upstream.", "Require a sanitization step or render as normal JSX/text."),
        _detector_record("permissive_cors", "Avoid wildcard CORS on sensitive APIs", "security", "cors", ["javascript", "typescript", "python"], "medium", "cors({ origin: '*' })", "Restrict origins to the deployed frontend domains.", "CORS configured with wildcard origin", "Public read-only APIs may intentionally allow wildcard CORS.", "Set an explicit allowlist and review credential/cookie behavior."),
        _detector_record("debug_config_enabled", "Disable debug/development configuration in production code", "production_readiness", "configuration", ["javascript", "typescript", "python"], "medium", "DEBUG=True or debug:true", "Use environment-specific config that defaults safely in production.", "debug/development flag enabled in source", "Local-only examples/tests may intentionally enable debug.", "Move debug mode behind explicit local environment configuration."),
        _detector_record("weak_crypto_hash", "Avoid weak cryptographic hashes in security contexts", "security", "cryptography", ["javascript", "typescript", "python"], "medium", "md5(password) or sha1(token)", "Use modern algorithms such as SHA-256/HMAC for integrity or bcrypt/argon2 for passwords.", "MD5/SHA1 near password/token/secret/auth code", "Non-security checksums are not credential hashing evidence.", "Choose a fit-for-purpose modern primitive and document the security goal."),
        _detector_record("insecure_random_secret", "Use cryptographic randomness for secrets", "security", "cryptography", ["javascript", "typescript", "python"], "medium", "Math.random() for reset token", "Use crypto.randomBytes/secrets.token_urlsafe.", "Math.random/random module near token/session/secret code", "UI randomness or sampling not used for security is not a finding.", "Use the platform cryptographic RNG for tokens, nonces, passwords, and reset codes."),
        _detector_record("sensitive_logging", "Do not write secrets or credentials to logs", "security", "logging", ["javascript", "typescript", "python"], "medium", "logger.info(password)", "Log stable identifiers and redact sensitive fields.", "password/token/secret/api key passed to logger/console", "Logging a constant field name without the sensitive value may be acceptable.", "Redact or omit sensitive values before logging."),
        _detector_record("blocking_call_in_async", "Avoid blocking operations inside async handlers", "performance", "async", ["javascript", "typescript", "python"], "medium", "time.sleep inside async def", "Use async equivalents or offload CPU/blocking work to a worker/thread.", "time.sleep/execSync/readFileSync inside async code", "Short startup scripts outside request paths are lower risk.", "Replace blocking calls with async APIs or explicit worker/thread offload."),
        _detector_record("unsafe_tempfile", "Use safe temporary-file APIs", "security", "filesystem", ["javascript", "typescript", "python"], "medium", "tempfile.mktemp()", "Use NamedTemporaryFile/mkstemp or a safe temp library that opens atomically.", "predictable temp filename generation", "Generated names that are immediately opened atomically are safer.", "Create temporary files atomically with restrictive permissions."),
        _detector_record("unsafe_redirect", "Validate user-controlled redirect targets", "security", "redirect", ["javascript", "typescript", "python"], "medium", "res.redirect(req.query.next)", "Allow only relative paths or allowlisted hosts.", "redirect target comes directly from request input", "Fixed server routes are not open redirect evidence.", "Normalize and allowlist redirect destinations."),
        _detector_record("frontend_token_storage", "Avoid persistent browser storage for auth tokens", "security", "frontend-auth", ["javascript", "typescript"], "medium", "localStorage.setItem('token', token)", "Prefer HttpOnly cookies or in-memory token state.", "localStorage/sessionStorage stores token-like key", "Public non-sensitive keys are not auth tokens.", "Move sensitive auth tokens out of script-readable persistent storage."),
        _detector_record("plaintext_password_handling", "Hash or verify passwords at the boundary", "security", "password-storage", ["javascript", "typescript", "python"], "high", "password = req.body.password", "Immediately verify against a slow hash or hash before storage.", "password read from request input without visible hashing/verification context", "Password comparison inside a framework auth helper may already be safe.", "Use framework password hashing/verification and avoid storing plaintext."),
        _detector_record("js_numeric_coercion_default", "Validate numeric conversion instead of defaulting invalid values", "correctness", "input-coercion", ["javascript", "typescript"], "medium", "Number(value) || 0", "Check Number.isNaN and reject/report invalid values explicitly.", "Number(...) || 0", "A deliberate UI display fallback may be acceptable if not persisted or used for business logic.", "Separate parsing from fallback behavior and handle invalid input explicitly."),
        _detector_record("js_date_slice_without_validation", "Validate date-like values before slicing", "correctness", "date-validation", ["javascript", "typescript"], "low", "tx.date.slice(0, 10)", "Parse and validate date strings before formatting.", ".date/.createdAt/.updatedAt .slice call", "A strongly typed Date/string invariant proven nearby lowers risk.", "Check type and date validity before slicing or formatting."),
        _detector_record("date_component_range_overflow", "Validate month/day range before constructing a Date", "correctness", "date-validation", ["javascript", "typescript", "python"], "medium", "new Date(year, 13, 1) // JS silently rolls month 13 into next January", "Validate month is 1-12 and day is within the month's actual range before constructing/parsing a date, or use a strict parsing library that rejects out-of-range components.", "a month/day-like numeric value used to construct a Date/date string with no upper/lower bound check first", "Values already validated by a schema/library immediately before use are lower risk.", "Reject out-of-range month/day values explicitly instead of relying on the date API's silent overflow/normalization behavior."),
        _detector_record("js_zero_baseline_fallback", "Handle zero baselines explicitly", "correctness", "numeric-boundary", ["javascript", "typescript"], "low", "if (!previous) return 0", "Distinguish null/undefined from numeric zero.", "falsy guard on previous/baseline before percentage calculation", "If zero truly means absent by domain contract, document that invariant.", "Use explicit nullish checks and define zero-baseline semantics."),
        _detector_record("js_unknown_type_default", "Reject unknown enum/type values explicitly", "correctness", "enum-validation", ["javascript", "typescript"], "low", "if (tx.type === 'credit') ... else ...", "Use switch/explicit branches and reject unknown values.", "single known type branch followed by catch-all else", "A preceding schema validation can make this safe.", "Validate enum values at the boundary and avoid silent default classification."),
        _detector_record("TEST-GEN-002", "Add regression tests for fixed bugs", "testing", "regression", ["any"], "medium", "bug fix with no regression test", "Add a focused test that fails before the fix and passes after.", "changed bug-prone behavior with no nearby test", "Pure copy or text-only changes may not need regression tests.", "Capture the reported failure mode as a durable regression test."),
        _detector_record("TEST-GEN-003", "Keep integration tests around external boundaries", "testing", "integration", ["any"], "medium", "API/database boundary changes with unit tests only", "Add integration coverage for route, DB, queue, or filesystem boundary behavior.", "boundary behavior changed without end-to-end/integration assertion", "Small pure functions may only need unit tests.", "Test the real boundary contract with realistic inputs and failure cases."),
        _detector_record("OBS-GEN-003", "Emit metrics for critical production flows", "reliability", "metrics", ["any"], "medium", "no metric for queue lag/error rate", "Track latency, error rate, saturation, and business-critical counters.", "critical flow has logging only and no metric/alert signal", "Tiny internal scripts may not need metrics.", "Add metrics and alerts for failure modes operators must see."),
        _detector_record("OBS-GEN-004", "Capture exceptions in error tracking", "reliability", "error-tracking", ["any"], "medium", "exceptions only printed to stdout", "Report unexpected exceptions to an error tracker with redaction.", "catch-all logs with no alert/error reporting path", "Local CLI tools may rely on process exit instead.", "Route unexpected errors to an error tracking/alerting system."),
        _detector_record("REL-GEN-004", "Use circuit breakers or bulkheads for unreliable dependencies", "reliability", "failure-isolation", ["any"], "medium", "unbounded calls to a flaky dependency", "Set timeouts, retries, and circuit breaker/bulkhead isolation.", "critical path calls downstream dependency with no isolation", "Low-volume admin scripts may be acceptable.", "Bound and isolate dependency failure so it does not cascade."),
        _detector_record("REL-GEN-005", "Clean up resources deterministically", "reliability", "resource-cleanup", ["any"], "medium", "open file/socket/session never closed", "Use context managers/finally/dispose hooks.", "resource acquired without visible close/dispose/finally", "Long-lived process-wide pools may intentionally stay open.", "Tie resource lifetime to a context manager or explicit cleanup path."),
        _detector_record("API-GEN-008", "Publish and validate API contracts", "api_design", "documentation", ["any"], "low", "route behavior changed without OpenAPI/schema docs", "Keep OpenAPI/JSON Schema/docs aligned with handlers.", "API route lacks request/response contract documentation", "Private prototypes may defer formal docs briefly.", "Document request, response, errors, and auth requirements."),
        _detector_record("DB-GEN-006", "Back up and restore production data", "database", "backup-restore", ["any"], "high", "no backup/restore plan for persistent data", "Automate backups and regularly test restores.", "persistent database introduced without backup evidence", "Ephemeral cache-only stores may not need backups.", "Define backup retention, encryption, restore testing, and ownership."),
        _detector_record("FE-GEN-005", "Meet baseline accessibility requirements", "architecture", "frontend-accessibility", ["javascript", "typescript"], "medium", "clickable div without keyboard support", "Use semantic controls, labels, focus states, and keyboard access.", "interactive UI lacks semantic element/label/focus handling", "Pure decorative elements are not interactive controls.", "Use semantic HTML and test keyboard/screen-reader behavior."),
    ]
)

