from knowledge.schema import KnowledgeRecord


KNOWLEDGE_RECORDS = [
    KnowledgeRecord(
        rule_id="SEC-GEN-001",
        title="Avoid hardcoded secrets",
        category="security",
        subcategory="secrets",
        language=["any"],
        framework=["any"],
        severity="critical",
        description="Credentials, API keys, tokens, and passwords must not be committed in source code.",
        why_it_matters="Leaked secrets allow unauthorized access and are difficult to fully rotate after exposure.",
        bad_patterns=["password = 'literal'", "api_key = 'literal'", "const token = 'literal'"],
        good_patterns=["Read secrets from environment variables or a managed secret store."],
        exceptions=["Clearly fake examples in documentation or tests should not be treated as live credentials."],
        detection_hints=["credential-like assignment to a long quoted literal", "exclude comments and obvious examples"],
        fix_strategy="Move the value to environment-backed configuration and rotate any exposed credential.",
        production_impact="Secret exposure can compromise accounts, data, and downstream services.",
        standards=[{"name": "CWE", "reference": "CWE-798 Use of Hard-coded Credentials"}],
        source_urls=["https://cwe.mitre.org/data/definitions/798.html"],
        content="Hardcoded secrets are production security defects unless the surrounding evidence proves the value is non-sensitive.",
    ),
    KnowledgeRecord(
        rule_id="SEC-PY-002",
        title="Avoid command execution through a shell",
        category="security",
        subcategory="command-injection",
        language=["python"],
        framework=["any"],
        severity="high",
        description="Python subprocess calls with shell=True execute through a shell and expand metacharacters.",
        why_it_matters="If user-controlled data reaches the command string, attackers can execute arbitrary commands.",
        bad_patterns=["subprocess.run(user_input, shell=True)", "subprocess.Popen(cmd, shell=True)"],
        good_patterns=["Pass an argv list with shell=False and validate allowed arguments."],
        exceptions=["Static literal maintenance scripts outside request paths may be lower risk but still need review."],
        detection_hints=["subprocess.* shell=True", "os.system", "commands built from request/query/form values"],
        fix_strategy="Replace shell=True with a list of fixed executable and validated arguments.",
        production_impact="Remote command execution can lead to full host compromise.",
        standards=[{"name": "CWE", "reference": "CWE-78 OS Command Injection"}],
        source_urls=["https://cwe.mitre.org/data/definitions/78.html"],
        content="Evidence should include both the dangerous API and data-flow or route context when available.",
    ),
    KnowledgeRecord(
        rule_id="PERF-WEB-001",
        title="Move expensive request-path work to background workers",
        category="performance",
        subcategory="blocking-work",
        language=["javascript", "typescript", "python"],
        framework=["express", "fastapi", "node"],
        severity="medium",
        description="CPU-heavy or long-running tasks in HTTP handlers block responses and reduce throughput.",
        why_it_matters="Users experience timeouts and the server can become unavailable under modest concurrency.",
        bad_patterns=["image/video processing inside a route", "large synchronous loops in a controller"],
        good_patterns=["Enqueue work to a background worker and return a job id/status endpoint."],
        exceptions=["Small bounded operations with measured latency may be acceptable."],
        detection_hints=["route handler calls image processing, crypto loops, sync filesystem, or repeated external calls"],
        fix_strategy="Introduce a queue/worker using the project's existing runtime conventions before adding new infrastructure.",
        production_impact="Prevents request timeouts and improves resilience under load.",
        standards=[{"name": "General", "reference": "Web request latency and background job design"}],
        source_urls=[],
        content="Use this when evidence shows expensive work runs synchronously in a request path.",
    ),
    KnowledgeRecord(
        rule_id="ARCH-GEN-001",
        title="Keep route handlers thin",
        category="architecture",
        subcategory="separation-of-concerns",
        language=["javascript", "typescript", "python"],
        framework=["express", "fastapi"],
        severity="medium",
        description="Routes should coordinate validation/auth and delegate business logic to services.",
        why_it_matters="Controllers that mix HTTP, business, and database logic become hard to test and change safely.",
        bad_patterns=["database writes and business decisions directly inside route handlers"],
        good_patterns=["route -> middleware/validation -> controller/service -> repository/database"],
        exceptions=["Tiny endpoints may inline trivial reads if the project convention already does so."],
        detection_hints=["route decorators or app.METHOD calls containing database calls or large logic blocks"],
        fix_strategy="Extract cohesive logic into the existing service/repository layer rather than introducing broad rewrites.",
        production_impact="Improves testability, change isolation, and incident debugging.",
        standards=[{"name": "General", "reference": "Separation of concerns"}],
        source_urls=[],
        content="Architecture findings require file/context evidence, not generic recommendations.",
    ),
    KnowledgeRecord(
        rule_id="API-GEN-001",
        title="Validate external input at API boundaries",
        category="api_design",
        subcategory="validation",
        language=["javascript", "typescript", "python"],
        framework=["express", "fastapi"],
        severity="high",
        description="Requests should be validated before data reaches services or persistence.",
        why_it_matters="Missing validation allows malformed data, injection payloads, and inconsistent records.",
        bad_patterns=["route directly uses req.body or request.json without schema/middleware"],
        good_patterns=["Pydantic models, Zod/Joi schemas, or explicit validation middleware before handlers"],
        exceptions=["Read-only endpoints with no external parameters may not need a schema."],
        detection_hints=["route middleware chain lacks validators; handler writes request fields to db"],
        fix_strategy="Use the validation approach already present in the project and verify middleware order.",
        production_impact="Reduces security defects and production data integrity failures.",
        standards=[{"name": "OWASP", "reference": "OWASP API Security Top 10"}],
        source_urls=["https://owasp.org/API-Security/"],
        content="Search related middleware before claiming validation is missing.",
    ),
]
